services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  yourapiname:
    container_name: yourcontainername
    image: yourimagepath
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped


networks:
  db:
    driver: bridge

volumes:
  db:
